"""数据库层——连接管理见 connection，SQL 操作见 queries。"""
from __future__ import annotations

# 连接管理和 schema 初始化
from .connection import (
    get_connection,
    get_db,
    init_db,
    DB_PATH,
    MOOD_KEYWORD_MAP,
)

# 所有 SQL 操作函数
from .queries import (
    # 日记 CRUD
    save_diary_to_db,
    get_all_diaries_from_db,
    get_diary_stats,
    get_random_public_diary,
    increment_hug_count,
    get_diaries_by_date,
    get_diary_by_id,
    update_diary,
    delete_diary,
    # 日记多图
    set_diary_images,
    get_diary_images,
    get_multi_diary_images,
    # 公开日记广场
    _build_public_diary_where,
    _build_search_clause,
    count_public_diaries,
    list_public_diaries,
    get_public_diary_by_id,
    has_liked_public_diary,
    like_public_diary,
    unlike_public_diary,
    count_public_diary_likes,
    _anon_name,
    add_public_diary_comment,
    list_public_diary_comments,
    count_public_diary_comments,
    get_comment_by_id,
    save_comment_like,
    remove_comment_like,
    count_comment_likes,
    # 用户主页
    get_or_create_default_user,
    get_user_by_id,
    update_user_profile,
    get_user_profile_stats,
    get_user_recent_public_diaries,
    get_user_mood_keywords,
    get_user_public_diary_count,
    search_users_by_keyword,
    # 用户认证
    get_user_by_username,
    create_user,
    update_user_password,
    ensure_default_user,
    # 关注系统
    follow_user,
    unfollow_user,
    is_following,
    get_following_count,
    get_follower_count,
    list_following_users,
    list_follower_users,
    get_following_recent_diaries,
    # 通知系统
    create_notification,
    notification_exists,
    list_notifications,
    count_unread_notifications,
    mark_notification_read,
    mark_all_notifications_read,
    delete_notification,
    # 打招呼系统
    create_greet_request,
    get_greet_request_by_id,
    get_pending_greet_between,
    get_latest_greet_between,
    has_accepted_greet_between,
    list_user_contacts,
    _attach_user_info,
    list_received_greet_requests,
    list_sent_greet_requests,
    update_greet_status,
    cancel_greet_request,
    count_pending_greet_requests,
    # 私信系统
    _ensure_user1_user2,
    get_or_create_conversation,
    get_conversation_by_id,
    get_conversation_between,
    list_user_conversations,
    create_private_message,
    list_private_messages,
    mark_conversation_read,
    count_unread_messages,
    count_conversation_unread,
    update_conversation_last_message,
    # 拉黑系统
    block_user,
    unblock_user,
    is_blocked_between,
    get_block_direction,
    has_blocked,
    list_blocked_users,
    count_blocked_users,
    get_blocked_user_ids,
    # 举报系统
    create_report,
    list_my_reports,
    get_report_by_id,
    count_my_reports,
    # 辅助查询
    get_diary_owner_id,
    get_comment_owner_or_diary_owner,
    get_message_participants,
    get_treehole_by_id,
    # 树洞
    get_or_create_treehole_identity,
    get_treehole_identity_by_id,
    save_treehole_reply,
    get_treehole_reply_full,
    list_treehole_replies,
    get_treehole_reply_owner_id,
    get_treehole_reply_by_id,
    save_treehole_reply_like,
    remove_treehole_reply_like,
    count_treehole_reply_likes,
    has_liked_treehole_reply,
    save_treehole_hug,
    remove_treehole_hug,
    has_hugged_treehole,
    decrement_hug_count,
    get_treehole_owner_id,
)
